In [2]:
import pandas as pd
df = pd.read_csv('311_Service_Requests_2020.csv')
df.head()

/Users/waiyu/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (20,31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,45285347,01/01/2020 12:00:00 AM,01/10/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11229.0,3442 NOSTRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.600129,-73.941843,"(40.6001292057807, -73.94184291675883)"
1,45285651,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,10458.0,2701 DECATUR AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.864866,-73.888783,"(40.86486556770799, -73.88878325729915)"
2,45285821,01/01/2020 12:00:00 AM,01/02/2020 09:50:09 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Other (Explain Below),11203.0,5707 CHURCH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.652536,-73.923540,"(40.65253575905768, -73.92353994017134)"
3,45287907,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,3 or More,Restaurant/Bar/Deli/Bakery,11214.0,1602 SHORE PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.595653,-74.000173,"(40.59565343138651, -74.00017283917487)"
4,45288240,01/01/2020 12:00:00 AM,01/02/2020 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,11385.0,1717 CORNELIA STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700366,-73.905438,"(40.700366489799876, -73.90543829006366)"

In [9]:
def f(x):
    return x.split('/')[2].split(' ')[0]
df['year'] = df["Created Date"].apply(f)

In [10]:
df_10025 = df[df["Incident Zip"] == 10025.0]
reside_zhixing_excuse = df[df["Incident Zip"] == 10025.0]["Complaint Type"].value_counts()
a = reside_zhixing_excuse.head(10)

In [11]:
df_2020 = df_10025[df_10025.year == "2020"]

In [21]:
top10_2020 = df_2020.loc[df_2020["Complaint Type"].isin(a.index),:]

In [26]:
top10 = top10_2020.groupby("Complaint Type").count().sort_values(by=['Unique Key'],ascending = False)["Unique Key"]

In [29]:
top10

Complaint Type
Noise - Residential            2952
Noise - Street/Sidewalk        2128
HEAT/HOT WATER                 1885
Noise                          1131
Illegal Parking                 792
Noise - Vehicle                 787
Non-Emergency Police Matter     773
Rodent                          691
Illegal Fireworks               672
UNSANITARY CONDITION            565
Name: Unique Key, dtype: int64